dbPath = "./"
dbName = "zoobc.db"
configPath = "./"
nodeKeyFile = "node_keys.json"

# Peer
peerPort=8001
myAddress="127.0.0.1"
wellknownPeers=[]

apiRPCPort=3001
# comment out or set to 0 to disable http proxy, only enable in dev mode
apiHTTPPort=3031
ownerAccountAddress = "BCZEGOb3WNx3fDOVf9ZS4EjvOIv_UeW4TVBQJ_6tHKlE"
apiReqTimeoutSec=2

proofOfOwnershipReqTimeoutSec = 2